#spring:
#  application:
#    name: auction-service
#  profiles:
#    active: none
#  config:
#    import: optional:configserver:http://52.79.127.196:8071
#
#  cloud:
#    config:
#      profile: ${PROFILE}
#
#encrypt:
#  key: ${ENCRYPT_KEY}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auction
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/auction
      auto-index-creation: true
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create