spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auction
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/auction
      auto-index-creation: true
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create